[build]
  command = "export NETLIFY=true && pnpm install && pnpm run build --filter ./artifacts/api-server && pnpm run build --filter ./artifacts/nomad-compass"
  publish = "artifacts/nomad-compass/dist/public"
  functions = "artifacts/api-server/dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
