export interface TaxBracket {
  min: number;
  max: number | null;
  rate: number;
}

export interface LocationData {
  id: string;
  city: string;
  country: string;
  countryCode: string;
  emoji: string;
  region: string;
  tags: string[];
  tax: {
    taxationType: "territorial" | "worldwide" | "flat" | "zero" | "remittance";
    taxBrackets?: TaxBracket[];
    flatRate?: number;
    socialSecurityRate: number;
    employerPays: boolean;
    hasTaxTreaty: string[];
    specialRegimes?: string;
    taxResidencyNotes: string;
    remoteWorkerRegime?: string;
  };
  col: {
    monthlyRentUSD: number;
    monthlyFoodUSD: number;
    monthlyTransportUSD: number;
    monthlyUtilitiesUSD: number;
    monthlyOtherUSD: number;
    colIndex: number;
    internetSpeedMbps: number;
    coworkingDayPassUSD?: number;
  };
  qol: {
    qualityOfLifeScore: number;
    safetyIndex: number;
    healthcareIndex: number;
    climateScore: number;
    englishFriendly: boolean;
    timeZone: string;
    timeZoneOffsetHours: number;
  };
  visa: {
    hasDigitalNomadVisa: boolean;
    visaName?: string;
    visaRequirements?: string;
    maxStayDays?: number;
    visaFeeUSD?: number;
    citizenshipPathYears?: number;
  };
  pros: string[];
  cons: string[];
}

export const LOCATIONS: LocationData[] = [
  {
    id: "pt-lisbon",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    emoji: "🇵🇹",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "english-friendly", "eu"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.20,
      socialSecurityRate: 0.11,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "CA", "AU", "BR", "IN", "JP", "SG"],
      specialRegimes: "NHR (Non-Habitual Resident): 20% flat income tax rate for 10 years",
      taxResidencyNotes: "Resident after 183 days. NHR regime available for first-time residents or those who haven't been resident in the past 5 years.",
      remoteWorkerRegime: "NHR 2.0 (IFICI): 20% flat rate on professional income for qualifying activities",
    },
    col: {
      monthlyRentUSD: 1350,
      monthlyFoodUSD: 500,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 130,
      monthlyOtherUSD: 300,
      colIndex: 48,
      internetSpeedMbps: 120,
      coworkingDayPassUSD: 20,
    },
    qol: {
      qualityOfLifeScore: 78,
      safetyIndex: 73,
      healthcareIndex: 75,
      climateScore: 85,
      englishFriendly: true,
      timeZone: "Europe/Lisbon",
      timeZoneOffsetHours: 0,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Digital Nomad Visa (D8)",
      visaRequirements: "Proof of income of at least 4x Portuguese minimum wage (~$4,200/month). Valid health insurance.",
      maxStayDays: 365,
      visaFeeUSD: 260,
      citizenshipPathYears: 5,
    },
    pros: ["NHR regime: 20% flat tax for 10 years", "EU access", "Warm climate", "Vibrant expat community", "Safe city"],
    cons: ["Rising cost of living", "Bureaucracy can be slow", "Crowded with tourists"],
  },
  {
    id: "pt-porto",
    city: "Porto",
    country: "Portugal",
    countryCode: "PT",
    emoji: "🇵🇹",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "eu"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.20,
      socialSecurityRate: 0.11,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "CA", "AU", "BR", "IN", "JP", "SG"],
      specialRegimes: "NHR: 20% flat income tax rate for 10 years",
      taxResidencyNotes: "Same NHR regime as Lisbon. Resident after 183 days.",
      remoteWorkerRegime: "NHR 2.0 (IFICI): 20% flat rate",
    },
    col: {
      monthlyRentUSD: 1050,
      monthlyFoodUSD: 430,
      monthlyTransportUSD: 70,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 250,
      colIndex: 42,
      internetSpeedMbps: 110,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 76,
      safetyIndex: 75,
      healthcareIndex: 74,
      climateScore: 78,
      englishFriendly: true,
      timeZone: "Europe/Lisbon",
      timeZoneOffsetHours: 0,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Digital Nomad Visa (D8)",
      visaRequirements: "Proof of income ~$4,200/month, valid health insurance",
      maxStayDays: 365,
      visaFeeUSD: 260,
      citizenshipPathYears: 5,
    },
    pros: ["NHR: 20% flat tax", "Cheaper than Lisbon", "Beautiful city", "Great food and wine scene"],
    cons: ["Fewer job opportunities locally", "Smaller international community"],
  },
  {
    id: "es-barcelona",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    emoji: "🇪🇸",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "english-friendly", "eu"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 12450, rate: 0.19 },
        { min: 12450, max: 20200, rate: 0.24 },
        { min: 20200, max: 35200, rate: 0.30 },
        { min: 35200, max: 60000, rate: 0.37 },
        { min: 60000, max: null, rate: 0.47 },
      ],
      socialSecurityRate: 0.066,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "CA", "AU", "MX", "AR", "JP"],
      specialRegimes: "Beckham Law: 24% flat rate for first 6 years for qualifying foreign workers",
      taxResidencyNotes: "Tax resident after 183 days. Beckham Law (SEPI) available for those who didn't reside in Spain in the 5 previous years.",
      remoteWorkerRegime: "Beckham Law: 24% flat rate on income up to €600K for 6 years",
    },
    col: {
      monthlyRentUSD: 1500,
      monthlyFoodUSD: 550,
      monthlyTransportUSD: 90,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 350,
      colIndex: 55,
      internetSpeedMbps: 140,
      coworkingDayPassUSD: 25,
    },
    qol: {
      qualityOfLifeScore: 80,
      safetyIndex: 65,
      healthcareIndex: 80,
      climateScore: 90,
      englishFriendly: true,
      timeZone: "Europe/Madrid",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Spain Digital Nomad Visa",
      visaRequirements: "Minimum income of 200% of Spanish minimum wage (~$3,400/month). Employment outside Spain.",
      maxStayDays: 365,
      visaFeeUSD: 80,
      citizenshipPathYears: 10,
    },
    pros: ["Beckham Law: 24% flat tax", "World-class lifestyle", "Mediterranean climate", "EU access"],
    cons: ["Petty theft common", "High standard cost of living", "Bureaucracy", "Noise"],
  },
  {
    id: "ee-tallinn",
    city: "Tallinn",
    country: "Estonia",
    countryCode: "EE",
    emoji: "🇪🇪",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "tech-friendly", "eu", "e-residency"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.20,
      socialSecurityRate: 0.00,
      employerPays: true,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "FI", "LV", "LT", "SE"],
      specialRegimes: "e-Residency: operate Estonian company with 0% tax on retained/reinvested profits",
      taxResidencyNotes: "Resident after 183 days. Freelancers/companies pay 0% on reinvested profits, 20% on distributions.",
      remoteWorkerRegime: "e-Residency OÜ: pay yourself dividends, 20% on distributions only",
    },
    col: {
      monthlyRentUSD: 900,
      monthlyFoodUSD: 380,
      monthlyTransportUSD: 60,
      monthlyUtilitiesUSD: 150,
      monthlyOtherUSD: 250,
      colIndex: 40,
      internetSpeedMbps: 130,
      coworkingDayPassUSD: 18,
    },
    qol: {
      qualityOfLifeScore: 74,
      safetyIndex: 80,
      healthcareIndex: 72,
      climateScore: 40,
      englishFriendly: true,
      timeZone: "Europe/Tallinn",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Estonia Digital Nomad Visa",
      visaRequirements: "Minimum income of €3,500/month. Employed by a company outside Estonia.",
      maxStayDays: 365,
      visaFeeUSD: 100,
      citizenshipPathYears: 8,
    },
    pros: ["Most digital government in the world", "e-Residency for low-tax company structure", "EU access", "Safe"],
    cons: ["Cold winters", "Smaller city", "Limited nightlife"],
  },
  {
    id: "cz-prague",
    city: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    emoji: "🇨🇿",
    region: "Europe",
    tags: ["low-cost", "eu", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 36000, rate: 0.15 },
        { min: 36000, max: null, rate: 0.23 },
      ],
      socialSecurityRate: 0.092,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "SK", "AT"],
      taxResidencyNotes: "Resident after 183 days. Flat 15% up to 48x average wage, 23% above.",
    },
    col: {
      monthlyRentUSD: 900,
      monthlyFoodUSD: 380,
      monthlyTransportUSD: 30,
      monthlyUtilitiesUSD: 140,
      monthlyOtherUSD: 250,
      colIndex: 40,
      internetSpeedMbps: 90,
      coworkingDayPassUSD: 18,
    },
    qol: {
      qualityOfLifeScore: 76,
      safetyIndex: 78,
      healthcareIndex: 74,
      climateScore: 55,
      englishFriendly: true,
      timeZone: "Europe/Prague",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Standard long-stay visa or freelancer visa available",
      citizenshipPathYears: 10,
    },
    pros: ["Low cost of living", "Beautiful city center", "Good public transport", "EU access"],
    cons: ["No specific nomad visa", "Cold winters", "Crowded tourist areas"],
  },
  {
    id: "hu-budapest",
    city: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    emoji: "🇭🇺",
    region: "Europe",
    tags: ["low-cost", "low-tax", "eu"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.15,
      socialSecurityRate: 0.185,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "AT", "RO"],
      taxResidencyNotes: "Flat 15% personal income tax — one of the lowest in the EU.",
    },
    col: {
      monthlyRentUSD: 750,
      monthlyFoodUSD: 320,
      monthlyTransportUSD: 30,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 220,
      colIndex: 38,
      internetSpeedMbps: 100,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 72,
      safetyIndex: 72,
      healthcareIndex: 65,
      climateScore: 58,
      englishFriendly: true,
      timeZone: "Europe/Budapest",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "White Card (Fehér Kártya)",
      visaRequirements: "Remote worker visa, income requirements apply",
      maxStayDays: 365,
      visaFeeUSD: 110,
      citizenshipPathYears: 8,
    },
    pros: ["15% flat income tax", "Very affordable", "Vibrant nightlife", "EU access"],
    cons: ["Language barrier", "Political climate concerns", "Aging infrastructure in areas"],
  },
  {
    id: "ro-bucharest",
    city: "Bucharest",
    country: "Romania",
    countryCode: "RO",
    emoji: "🇷🇴",
    region: "Europe",
    tags: ["low-cost", "low-tax", "eu"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.10,
      socialSecurityRate: 0.25,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "IT"],
      taxResidencyNotes: "10% flat income tax — among the lowest in the EU. High social security though.",
    },
    col: {
      monthlyRentUSD: 600,
      monthlyFoodUSD: 280,
      monthlyTransportUSD: 30,
      monthlyUtilitiesUSD: 100,
      monthlyOtherUSD: 200,
      colIndex: 30,
      internetSpeedMbps: 170,
      coworkingDayPassUSD: 12,
    },
    qol: {
      qualityOfLifeScore: 65,
      safetyIndex: 65,
      healthcareIndex: 55,
      climateScore: 58,
      englishFriendly: true,
      timeZone: "Europe/Bucharest",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Romania Digital Nomad Visa",
      visaRequirements: "Proof of monthly income of at least 3x the Romanian national gross average salary (~$3,000)",
      maxStayDays: 365,
      visaFeeUSD: 60,
      citizenshipPathYears: 8,
    },
    pros: ["10% flat income tax", "Very cheap", "Excellent internet speeds", "EU access"],
    cons: ["Infrastructure gaps", "Healthcare quality varies", "Bureaucracy"],
  },
  {
    id: "bg-sofia",
    city: "Sofia",
    country: "Bulgaria",
    countryCode: "BG",
    emoji: "🇧🇬",
    region: "Europe",
    tags: ["low-cost", "low-tax", "eu"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.10,
      socialSecurityRate: 0.138,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "RU"],
      taxResidencyNotes: "10% flat income tax — one of the lowest rates in the world for an EU country.",
    },
    col: {
      monthlyRentUSD: 550,
      monthlyFoodUSD: 260,
      monthlyTransportUSD: 25,
      monthlyUtilitiesUSD: 90,
      monthlyOtherUSD: 180,
      colIndex: 28,
      internetSpeedMbps: 145,
      coworkingDayPassUSD: 10,
    },
    qol: {
      qualityOfLifeScore: 62,
      safetyIndex: 62,
      healthcareIndex: 55,
      climateScore: 60,
      englishFriendly: false,
      timeZone: "Europe/Sofia",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: false,
      citizenshipPathYears: 5,
    },
    pros: ["10% flat income tax", "Cheapest EU capital", "Fast growing tech scene"],
    cons: ["Limited English speakers", "Air quality issues in winter", "No nomad visa"],
  },
  {
    id: "de-berlin",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    emoji: "🇩🇪",
    region: "Europe",
    tags: ["tech-friendly", "eu", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 11604, rate: 0 },
        { min: 11604, max: 62810, rate: 0.42 },
        { min: 62810, max: 277826, rate: 0.42 },
        { min: 277826, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.095,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "FR", "JP", "CN", "AU", "CA"],
      taxResidencyNotes: "High progressive taxes. Solidarity surcharge (Soli) applies to high earners. Church tax optional (~8-9%).",
    },
    col: {
      monthlyRentUSD: 1800,
      monthlyFoodUSD: 600,
      monthlyTransportUSD: 100,
      monthlyUtilitiesUSD: 180,
      monthlyOtherUSD: 400,
      colIndex: 64,
      internetSpeedMbps: 80,
      coworkingDayPassUSD: 30,
    },
    qol: {
      qualityOfLifeScore: 82,
      safetyIndex: 70,
      healthcareIndex: 86,
      climateScore: 50,
      englishFriendly: true,
      timeZone: "Europe/Berlin",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaName: "Freelancer Visa (Freiberufler)",
      visaRequirements: "Proof of clients/income. Non-EU nationals need freelancer or work visa.",
      citizenshipPathYears: 8,
    },
    pros: ["Strong legal protections", "Excellent healthcare", "Thriving tech scene", "EU access"],
    cons: ["Very high taxes (up to 45%)", "Bureaucratic", "Cold winters", "Rising rents"],
  },
  {
    id: "nl-amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    emoji: "🇳🇱",
    region: "Europe",
    tags: ["english-friendly", "eu", "tech-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 75518, rate: 0.369 },
        { min: 75518, max: null, rate: 0.495 },
      ],
      socialSecurityRate: 0.00,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN"],
      specialRegimes: "30% Ruling: tax-free reimbursement of 30% of salary for qualifying expats for 5 years",
      taxResidencyNotes: "Resident after 183 days. 30% ruling reduces effective rate significantly for expats.",
      remoteWorkerRegime: "30% ruling: treats 30% of income as tax-free expense allowance for up to 5 years",
    },
    col: {
      monthlyRentUSD: 2200,
      monthlyFoodUSD: 650,
      monthlyTransportUSD: 100,
      monthlyUtilitiesUSD: 180,
      monthlyOtherUSD: 450,
      colIndex: 75,
      internetSpeedMbps: 140,
      coworkingDayPassUSD: 35,
    },
    qol: {
      qualityOfLifeScore: 85,
      safetyIndex: 72,
      healthcareIndex: 88,
      climateScore: 45,
      englishFriendly: true,
      timeZone: "Europe/Amsterdam",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: false,
      citizenshipPathYears: 5,
    },
    pros: ["30% ruling reduces effective tax rate", "English widely spoken", "Excellent quality of life", "EU access"],
    cons: ["Very expensive", "High baseline taxes", "Weather is poor", "Housing crisis"],
  },
  {
    id: "ae-dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    emoji: "🇦🇪",
    region: "Middle East",
    tags: ["zero-tax", "digital-nomad-visa", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "zero",
      flatRate: 0,
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: [],
      taxResidencyNotes: "No personal income tax in the UAE. Corporate tax introduced in 2023 (9% on profits over AED 375K) but does not apply to personal employment income.",
    },
    col: {
      monthlyRentUSD: 2200,
      monthlyFoodUSD: 600,
      monthlyTransportUSD: 200,
      monthlyUtilitiesUSD: 200,
      monthlyOtherUSD: 500,
      colIndex: 72,
      internetSpeedMbps: 150,
      coworkingDayPassUSD: 40,
    },
    qol: {
      qualityOfLifeScore: 75,
      safetyIndex: 88,
      healthcareIndex: 78,
      climateScore: 65,
      englishFriendly: true,
      timeZone: "Asia/Dubai",
      timeZoneOffsetHours: 4,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "UAE Freelancer/Remote Work Visa",
      visaRequirements: "Minimum income of $3,500/month. Employment contract or proof of self-employment.",
      maxStayDays: 365,
      visaFeeUSD: 300,
      citizenshipPathYears: 30,
    },
    pros: ["0% income tax", "World-class infrastructure", "Safe", "Global travel hub"],
    cons: ["Extremely hot summers", "High cost of living", "Very strict laws", "Limited cultural freedoms"],
  },
  {
    id: "sg-singapore",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    emoji: "🇸🇬",
    region: "Asia",
    tags: ["tech-friendly", "english-friendly", "low-tax"],
    tax: {
      taxationType: "territorial",
      taxBrackets: [
        { min: 0, max: 20000, rate: 0 },
        { min: 20000, max: 30000, rate: 0.02 },
        { min: 30000, max: 40000, rate: 0.035 },
        { min: 40000, max: 80000, rate: 0.07 },
        { min: 80000, max: 120000, rate: 0.115 },
        { min: 120000, max: 160000, rate: 0.15 },
        { min: 160000, max: 200000, rate: 0.18 },
        { min: 200000, max: 240000, rate: 0.19 },
        { min: 240000, max: 280000, rate: 0.195 },
        { min: 280000, max: 320000, rate: 0.20 },
        { min: 320000, max: null, rate: 0.22 },
      ],
      socialSecurityRate: 0.00,
      employerPays: true,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU"],
      taxResidencyNotes: "Territorial system: only Singapore-sourced income taxed. Foreign-sourced income not taxable unless remitted. Max effective rate is 22%.",
    },
    col: {
      monthlyRentUSD: 2800,
      monthlyFoodUSD: 700,
      monthlyTransportUSD: 120,
      monthlyUtilitiesUSD: 150,
      monthlyOtherUSD: 500,
      colIndex: 90,
      internetSpeedMbps: 240,
      coworkingDayPassUSD: 45,
    },
    qol: {
      qualityOfLifeScore: 88,
      safetyIndex: 95,
      healthcareIndex: 92,
      climateScore: 60,
      englishFriendly: true,
      timeZone: "Asia/Singapore",
      timeZoneOffsetHours: 8,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Employment Pass or Personalised Employment Pass (PEP) for self-employed. Minimum salary thresholds apply.",
      citizenshipPathYears: 10,
    },
    pros: ["Very safe", "Top-tier healthcare and infrastructure", "Low income tax", "Strategic Asian hub"],
    cons: ["Very expensive", "No nomad visa", "Hot and humid", "Strict laws"],
  },
  {
    id: "th-bangkok",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    emoji: "🇹🇭",
    region: "Asia",
    tags: ["digital-nomad-visa", "low-cost", "warm-climate", "low-tax"],
    tax: {
      taxationType: "remittance",
      taxBrackets: [
        { min: 0, max: 150000, rate: 0 },
        { min: 150000, max: 300000, rate: 0.05 },
        { min: 300000, max: 500000, rate: 0.10 },
        { min: 500000, max: 750000, rate: 0.15 },
        { min: 750000, max: 1000000, rate: 0.20 },
        { min: 1000000, max: 2000000, rate: 0.25 },
        { min: 2000000, max: 5000000, rate: 0.30 },
        { min: 5000000, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU", "SG"],
      specialRegimes: "LTR Visa holders with foreign-sourced income: 17% flat rate or exemption",
      taxResidencyNotes: "As of 2024: all income remitted to Thailand (even from prior years) is taxable. LTR visa holders working remotely for foreign companies: 17% flat tax or tax-free on income earned abroad.",
      remoteWorkerRegime: "LTR Visa (Long-Term Resident): 17% flat tax for remote workers earning $80K+/year",
    },
    col: {
      monthlyRentUSD: 800,
      monthlyFoodUSD: 350,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 100,
      monthlyOtherUSD: 250,
      colIndex: 38,
      internetSpeedMbps: 120,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 68,
      safetyIndex: 55,
      healthcareIndex: 72,
      climateScore: 70,
      englishFriendly: true,
      timeZone: "Asia/Bangkok",
      timeZoneOffsetHours: 7,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "LTR Visa (Long-Term Resident)",
      visaRequirements: "Must earn at least $80,000/year (or $40,000 with relevant degree). Work remotely for a foreign employer.",
      maxStayDays: 1825,
      visaFeeUSD: 200,
      citizenshipPathYears: 10,
    },
    pros: ["Low cost of living", "Great food", "Warm climate", "LTR visa for nomads", "World-class hospitals"],
    cons: ["Traffic and pollution", "Language barrier outside tourist areas", "Political instability risk"],
  },
  {
    id: "th-chiang-mai",
    city: "Chiang Mai",
    country: "Thailand",
    countryCode: "TH",
    emoji: "🇹🇭",
    region: "Asia",
    tags: ["digital-nomad-visa", "low-cost", "warm-climate"],
    tax: {
      taxationType: "remittance",
      taxBrackets: [
        { min: 0, max: 150000, rate: 0 },
        { min: 150000, max: 300000, rate: 0.05 },
        { min: 300000, max: 500000, rate: 0.10 },
        { min: 500000, max: 750000, rate: 0.15 },
        { min: 750000, max: null, rate: 0.20 },
      ],
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU", "SG"],
      specialRegimes: "LTR Visa: 17% flat for remote workers",
      taxResidencyNotes: "Same tax rules as Bangkok. LTR Visa available.",
      remoteWorkerRegime: "LTR Visa: 17% flat rate",
    },
    col: {
      monthlyRentUSD: 500,
      monthlyFoodUSD: 250,
      monthlyTransportUSD: 60,
      monthlyUtilitiesUSD: 70,
      monthlyOtherUSD: 150,
      colIndex: 26,
      internetSpeedMbps: 90,
      coworkingDayPassUSD: 10,
    },
    qol: {
      qualityOfLifeScore: 66,
      safetyIndex: 58,
      healthcareIndex: 65,
      climateScore: 72,
      englishFriendly: true,
      timeZone: "Asia/Bangkok",
      timeZoneOffsetHours: 7,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "LTR Visa (Long-Term Resident)",
      visaRequirements: "Earn $80,000+/year remotely for foreign employer",
      maxStayDays: 1825,
      visaFeeUSD: 200,
      citizenshipPathYears: 10,
    },
    pros: ["Legendary digital nomad hub", "Extremely cheap", "Great climate (outside summer)", "Huge expat community"],
    cons: ["Smoke season in Feb-April", "Less infrastructure than Bangkok", "Limited career networking"],
  },
  {
    id: "id-bali",
    city: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    emoji: "🇮🇩",
    region: "Asia",
    tags: ["digital-nomad-visa", "low-cost", "warm-climate"],
    tax: {
      taxationType: "territorial",
      flatRate: 0.00,
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["AU", "SG", "JP", "DE", "NL"],
      taxResidencyNotes: "Remote workers on Digital Nomad Visa: foreign-sourced income is NOT taxable in Indonesia. Must not be registered as a tax resident.",
    },
    col: {
      monthlyRentUSD: 700,
      monthlyFoodUSD: 300,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 80,
      monthlyOtherUSD: 200,
      colIndex: 30,
      internetSpeedMbps: 50,
      coworkingDayPassUSD: 12,
    },
    qol: {
      qualityOfLifeScore: 62,
      safetyIndex: 58,
      healthcareIndex: 50,
      climateScore: 82,
      englishFriendly: true,
      timeZone: "Asia/Makassar",
      timeZoneOffsetHours: 8,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Indonesia Digital Nomad Visa (E33G)",
      visaRequirements: "Work for a foreign company. Proof of income. Health insurance required.",
      maxStayDays: 365,
      visaFeeUSD: 200,
      citizenshipPathYears: undefined,
    },
    pros: ["0% tax on foreign income for visa holders", "Beautiful scenery", "Affordable lifestyle", "Strong nomad community"],
    cons: ["Internet can be unreliable", "Limited healthcare", "Traffic", "Tourist trap pricing"],
  },
  {
    id: "my-kuala-lumpur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    emoji: "🇲🇾",
    region: "Asia",
    tags: ["digital-nomad-visa", "low-cost", "english-friendly", "low-tax"],
    tax: {
      taxationType: "territorial",
      taxBrackets: [
        { min: 0, max: 5000, rate: 0 },
        { min: 5000, max: 20000, rate: 0.01 },
        { min: 20000, max: 35000, rate: 0.03 },
        { min: 35000, max: 50000, rate: 0.08 },
        { min: 50000, max: 70000, rate: 0.13 },
        { min: 70000, max: 100000, rate: 0.21 },
        { min: 100000, max: null, rate: 0.24 },
      ],
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "AU", "SG", "JP", "DE", "CN"],
      taxResidencyNotes: "Foreign-sourced income remitted to Malaysia is generally exempt for residents. Nomad visa holders: income from foreign sources not subject to Malaysian tax.",
      remoteWorkerRegime: "DE Rantau Digital Nomad Pass: foreign income tax-exempt",
    },
    col: {
      monthlyRentUSD: 700,
      monthlyFoodUSD: 300,
      monthlyTransportUSD: 70,
      monthlyUtilitiesUSD: 80,
      monthlyOtherUSD: 200,
      colIndex: 32,
      internetSpeedMbps: 100,
      coworkingDayPassUSD: 14,
    },
    qol: {
      qualityOfLifeScore: 66,
      safetyIndex: 58,
      healthcareIndex: 70,
      climateScore: 68,
      englishFriendly: true,
      timeZone: "Asia/Kuala_Lumpur",
      timeZoneOffsetHours: 8,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "DE Rantau Digital Nomad Pass",
      visaRequirements: "Min $24,000/year income. Work for non-Malaysian company.",
      maxStayDays: 365,
      visaFeeUSD: 500,
      citizenshipPathYears: undefined,
    },
    pros: ["Foreign income tax-exempt", "English widely spoken", "Affordable", "Great food scene"],
    cons: ["High humidity", "Traffic", "Limited nightlife options", "Somewhat conservative culture"],
  },
  {
    id: "ge-tbilisi",
    city: "Tbilisi",
    country: "Georgia",
    countryCode: "GE",
    emoji: "🇬🇪",
    region: "Europe",
    tags: ["low-cost", "low-tax", "digital-nomad-visa"],
    tax: {
      taxationType: "territorial",
      flatRate: 0.20,
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["DE", "AT", "FR", "IT", "UK"],
      specialRegimes: "Small Business Status: 1% turnover tax for freelancers earning under ~$157K/year",
      taxResidencyNotes: "Only Georgian-source income is taxed for residents. Foreign income is generally exempt. Freelancers can register as a 'Virtual Zone Person' (0% on IT services sold abroad) or Individual Entrepreneur (small business, 1% tax).",
      remoteWorkerRegime: "Small Business (Mikkro): 1% on all income. Virtual Zone: 0% on IT services exported",
    },
    col: {
      monthlyRentUSD: 550,
      monthlyFoodUSD: 280,
      monthlyTransportUSD: 40,
      monthlyUtilitiesUSD: 80,
      monthlyOtherUSD: 150,
      colIndex: 28,
      internetSpeedMbps: 85,
      coworkingDayPassUSD: 10,
    },
    qol: {
      qualityOfLifeScore: 62,
      safetyIndex: 70,
      healthcareIndex: 55,
      climateScore: 65,
      englishFriendly: false,
      timeZone: "Asia/Tbilisi",
      timeZoneOffsetHours: 4,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Remotely from Georgia",
      visaRequirements: "Employment contract with foreign company, proof of income. Citizens of 95+ countries can stay visa-free for 1 year.",
      maxStayDays: 365,
      visaFeeUSD: 0,
      citizenshipPathYears: undefined,
    },
    pros: ["1% tax as small business or 0% as Virtual Zone", "Very cheap", "Friendly locals", "Year-round entry for many nationalities"],
    cons: ["Limited healthcare", "Language barrier", "Political proximity to Russia", "Infrastructure gaps"],
  },
  {
    id: "mt-malta",
    city: "Malta",
    country: "Malta",
    countryCode: "MT",
    emoji: "🇲🇹",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "english-friendly", "eu"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 9100, rate: 0 },
        { min: 9100, max: 14500, rate: 0.15 },
        { min: 14500, max: 60000, rate: 0.25 },
        { min: 60000, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0.10,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "IT", "AU"],
      specialRegimes: "Malta Global Residence Programme: 15% flat rate on foreign income remitted to Malta",
      taxResidencyNotes: "Favorable remittance-based tax regime for qualifying residents.",
      remoteWorkerRegime: "Nomad Residence Permit: taxed under standard Maltese rates but with favorable exemptions",
    },
    col: {
      monthlyRentUSD: 1200,
      monthlyFoodUSD: 480,
      monthlyTransportUSD: 70,
      monthlyUtilitiesUSD: 130,
      monthlyOtherUSD: 300,
      colIndex: 52,
      internetSpeedMbps: 80,
      coworkingDayPassUSD: 22,
    },
    qol: {
      qualityOfLifeScore: 72,
      safetyIndex: 78,
      healthcareIndex: 74,
      climateScore: 88,
      englishFriendly: true,
      timeZone: "Europe/Malta",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Malta Nomad Residence Permit",
      visaRequirements: "Proof of employment with non-Malta company. Min income ~$2,700/month.",
      maxStayDays: 365,
      visaFeeUSD: 300,
      citizenshipPathYears: 5,
    },
    pros: ["EU citizenship path (5 years)", "English is official language", "Mediterranean climate", "Sunny 300 days/year"],
    cons: ["Small island", "Traffic on small roads", "Limited entertainment options", "Water can be scarce"],
  },
  {
    id: "cy-limassol",
    city: "Limassol",
    country: "Cyprus",
    countryCode: "CY",
    emoji: "🇨🇾",
    region: "Europe",
    tags: ["low-tax", "warm-climate", "english-friendly", "eu"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 19500, rate: 0 },
        { min: 19500, max: 28000, rate: 0.20 },
        { min: 28000, max: 36300, rate: 0.25 },
        { min: 36300, max: 60000, rate: 0.30 },
        { min: 60000, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0.088,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "RU", "IN"],
      specialRegimes: "Non-Dom Status: no tax on dividends, interest, or capital gains for 17 years",
      taxResidencyNotes: "Non-dom status: dividend and interest income are completely exempt. Only salary/business income taxed at progressive rates.",
      remoteWorkerRegime: "Non-Dom: 0% on dividends and passive income, 50% exemption on employment income > €100K",
    },
    col: {
      monthlyRentUSD: 1300,
      monthlyFoodUSD: 500,
      monthlyTransportUSD: 120,
      monthlyUtilitiesUSD: 150,
      monthlyOtherUSD: 320,
      colIndex: 55,
      internetSpeedMbps: 75,
      coworkingDayPassUSD: 22,
    },
    qol: {
      qualityOfLifeScore: 72,
      safetyIndex: 80,
      healthcareIndex: 68,
      climateScore: 90,
      englishFriendly: true,
      timeZone: "Asia/Nicosia",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: false,
      citizenshipPathYears: 7,
    },
    pros: ["Non-dom status: 0% on dividends/passive income", "Warm Mediterranean climate", "English everywhere", "EU member"],
    cons: ["Divided island (north/south)", "Car necessary", "Limited direct flights", "Small country"],
  },
  {
    id: "mx-mexico-city",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    emoji: "🇲🇽",
    region: "Americas",
    tags: ["low-cost", "digital-nomad-visa", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 7735, rate: 0.016 },
        { min: 7735, max: 65651, rate: 0.064 },
        { min: 65651, max: 115375, rate: 0.108 },
        { min: 115375, max: 134119, rate: 0.16 },
        { min: 134119, max: 160577, rate: 0.176 },
        { min: 160577, max: 323862, rate: 0.212 },
        { min: 323862, max: 510451, rate: 0.232 },
        { min: 510451, max: 756104, rate: 0.30 },
        { min: 756104, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0.00,
      employerPays: true,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "CA", "JP", "ES"],
      taxResidencyNotes: "Mexico taxes worldwide income of residents. Non-residents: only Mexican-sourced income. Many remote workers on tourist/nomad status avoid Mexican tax residency.",
    },
    col: {
      monthlyRentUSD: 800,
      monthlyFoodUSD: 350,
      monthlyTransportUSD: 50,
      monthlyUtilitiesUSD: 80,
      monthlyOtherUSD: 200,
      colIndex: 38,
      internetSpeedMbps: 70,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 60,
      safetyIndex: 40,
      healthcareIndex: 62,
      climateScore: 80,
      englishFriendly: true,
      timeZone: "America/Mexico_City",
      timeZoneOffsetHours: -6,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Temporary Resident Visa for income earners. Stay up to 180 days without visa as tourist.",
      maxStayDays: 180,
      citizenshipPathYears: 5,
    },
    pros: ["Cheap cost of living", "Great food culture", "Close timezone to US employers", "Vibrant expat community in Roma/Condesa"],
    cons: ["Safety concerns", "Air pollution", "Traffic", "Bureaucratic tax setup as legal resident"],
  },
  {
    id: "co-medellin",
    city: "Medellin",
    country: "Colombia",
    countryCode: "CO",
    emoji: "🇨🇴",
    region: "Americas",
    tags: ["low-cost", "digital-nomad-visa", "warm-climate"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 43000, rate: 0 },
        { min: 43000, max: 79000, rate: 0.19 },
        { min: 79000, max: 112000, rate: 0.28 },
        { min: 112000, max: 143000, rate: 0.33 },
        { min: 143000, max: null, rate: 0.39 },
      ],
      socialSecurityRate: 0.00,
      employerPays: false,
      hasTaxTreaty: ["ES", "CA", "CL", "CH", "IN"],
      taxResidencyNotes: "Non-residents only pay on Colombian-sourced income (flat 35%). Resident if you spend 183+ days/year. No US/UK tax treaty.",
    },
    col: {
      monthlyRentUSD: 650,
      monthlyFoodUSD: 280,
      monthlyTransportUSD: 40,
      monthlyUtilitiesUSD: 70,
      monthlyOtherUSD: 170,
      colIndex: 30,
      internetSpeedMbps: 80,
      coworkingDayPassUSD: 12,
    },
    qol: {
      qualityOfLifeScore: 60,
      safetyIndex: 40,
      healthcareIndex: 58,
      climateScore: 82,
      englishFriendly: false,
      timeZone: "America/Bogota",
      timeZoneOffsetHours: -5,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Colombia Digital Nomad Visa",
      visaRequirements: "Proof of employment outside Colombia, min $750/month income",
      maxStayDays: 365,
      visaFeeUSD: 52,
      citizenshipPathYears: 5,
    },
    pros: ["Eternal spring climate", "Very affordable", "Growing tech scene", "Diverse culture"],
    cons: ["Safety concerns in some areas", "Language barrier", "Infrastructure gaps", "No treaty with US/UK"],
  },
  {
    id: "pa-panama-city",
    city: "Panama City",
    country: "Panama",
    countryCode: "PA",
    emoji: "🇵🇦",
    region: "Americas",
    tags: ["low-tax", "digital-nomad-visa", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "territorial",
      flatRate: 0,
      socialSecurityRate: 0.0975,
      employerPays: false,
      hasTaxTreaty: ["ES", "MX", "LU", "QA", "AE", "SG", "KR"],
      taxResidencyNotes: "Pure territorial taxation. Only income generated from activities within Panama is taxed. Foreign-sourced income is 100% exempt — regardless of where you live.",
    },
    col: {
      monthlyRentUSD: 900,
      monthlyFoodUSD: 400,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 130,
      monthlyOtherUSD: 250,
      colIndex: 42,
      internetSpeedMbps: 65,
      coworkingDayPassUSD: 18,
    },
    qol: {
      qualityOfLifeScore: 62,
      safetyIndex: 50,
      healthcareIndex: 65,
      climateScore: 65,
      englishFriendly: true,
      timeZone: "America/Panama",
      timeZoneOffsetHours: -5,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Panama Short Stay Visa (Remote Worker)",
      visaRequirements: "Proof of employment outside Panama, bank statements",
      maxStayDays: 365,
      visaFeeUSD: 300,
      citizenshipPathYears: 5,
    },
    pros: ["0% tax on foreign-sourced income", "USD economy", "Easy residency options", "Good healthcare"],
    cons: ["Extreme heat and humidity", "Traffic", "Safety varies by neighborhood"],
  },
  {
    id: "au-sydney",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    emoji: "🇦🇺",
    region: "Oceania",
    tags: ["english-friendly", "high-quality", "warm-climate"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 18200, rate: 0 },
        { min: 18200, max: 45000, rate: 0.19 },
        { min: 45000, max: 120000, rate: 0.325 },
        { min: 120000, max: 180000, rate: 0.37 },
        { min: 180000, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.02,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "SG", "NZ"],
      taxResidencyNotes: "Medicare levy of 2% on top of income tax. Foreign income taxed for residents. Tax offset available for some foreign income.",
    },
    col: {
      monthlyRentUSD: 2400,
      monthlyFoodUSD: 700,
      monthlyTransportUSD: 150,
      monthlyUtilitiesUSD: 180,
      monthlyOtherUSD: 500,
      colIndex: 82,
      internetSpeedMbps: 110,
      coworkingDayPassUSD: 35,
    },
    qol: {
      qualityOfLifeScore: 86,
      safetyIndex: 72,
      healthcareIndex: 85,
      climateScore: 82,
      englishFriendly: true,
      timeZone: "Australia/Sydney",
      timeZoneOffsetHours: 10,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Working Holiday Visa (up to 35), Skilled Migration stream, or Employer Sponsored visa",
      citizenshipPathYears: 4,
    },
    pros: ["Excellent quality of life", "Great healthcare", "Perfect weather", "Strong job market"],
    cons: ["High taxes", "Very expensive city", "Remote timezone from major markets", "No nomad visa"],
  },
  {
    id: "vn-ho-chi-minh",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    emoji: "🇻🇳",
    region: "Asia",
    tags: ["low-cost", "warm-climate"],
    tax: {
      taxationType: "territorial",
      taxBrackets: [
        { min: 0, max: 5000, rate: 0.05 },
        { min: 5000, max: 10000, rate: 0.10 },
        { min: 10000, max: 18000, rate: 0.15 },
        { min: 18000, max: 32000, rate: 0.20 },
        { min: 32000, max: 52000, rate: 0.25 },
        { min: 52000, max: 80000, rate: 0.30 },
        { min: 80000, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "KR", "SG", "AU", "CN"],
      taxResidencyNotes: "Non-residents taxed at flat 20% on Vietnam-sourced income only. Residents taxed progressively on worldwide income. Most remote workers avoid tax residency (under 183 days).",
    },
    col: {
      monthlyRentUSD: 600,
      monthlyFoodUSD: 250,
      monthlyTransportUSD: 50,
      monthlyUtilitiesUSD: 70,
      monthlyOtherUSD: 150,
      colIndex: 26,
      internetSpeedMbps: 60,
      coworkingDayPassUSD: 10,
    },
    qol: {
      qualityOfLifeScore: 58,
      safetyIndex: 55,
      healthcareIndex: 55,
      climateScore: 70,
      englishFriendly: false,
      timeZone: "Asia/Ho_Chi_Minh",
      timeZoneOffsetHours: 7,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "E-visa for up to 90 days for most nationalities. Visa extensions possible.",
      maxStayDays: 90,
      citizenshipPathYears: undefined,
    },
    pros: ["Extremely cheap", "Delicious food culture", "Warm climate", "Growing tech scene"],
    cons: ["No nomad visa", "Traffic chaos", "Language barrier", "Air pollution"],
  },
  {
    id: "bb-bridgetown",
    city: "Bridgetown",
    country: "Barbados",
    countryCode: "BB",
    emoji: "🇧🇧",
    region: "Americas",
    tags: ["digital-nomad-visa", "warm-climate", "english-friendly", "low-tax"],
    tax: {
      taxationType: "territorial",
      flatRate: 0,
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "CA"],
      taxResidencyNotes: "Welcome Stamp Visa holders: exempted from Barbados income tax on foreign-sourced income for the duration of the visa. Only Barbados-sourced income subject to local tax.",
    },
    col: {
      monthlyRentUSD: 1800,
      monthlyFoodUSD: 600,
      monthlyTransportUSD: 150,
      monthlyUtilitiesUSD: 200,
      monthlyOtherUSD: 400,
      colIndex: 62,
      internetSpeedMbps: 60,
      coworkingDayPassUSD: 30,
    },
    qol: {
      qualityOfLifeScore: 68,
      safetyIndex: 60,
      healthcareIndex: 65,
      climateScore: 92,
      englishFriendly: true,
      timeZone: "America/Barbados",
      timeZoneOffsetHours: -4,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Welcome Stamp Visa",
      visaRequirements: "Proof of employment outside Barbados, min income $50,000/year. Application fee.",
      maxStayDays: 365,
      visaFeeUSD: 2000,
      citizenshipPathYears: undefined,
    },
    pros: ["0% tax on foreign income", "English-speaking Caribbean paradise", "Stable government", "Great beaches"],
    cons: ["Expensive island prices", "Very high visa fee ($2,000)", "Limited activities beyond beach", "Hurricane risk"],
  },
  {
    id: "cr-san-jose",
    city: "San Jose",
    country: "Costa Rica",
    countryCode: "CR",
    emoji: "🇨🇷",
    region: "Americas",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "territorial",
      flatRate: 0,
      socialSecurityRate: 0,
      employerPays: false,
      hasTaxTreaty: ["US"],
      taxResidencyNotes: "Pure territorial taxation. Foreign-sourced income is 100% tax-exempt in Costa Rica. Nomad Visa holders explicitly exempt.",
    },
    col: {
      monthlyRentUSD: 900,
      monthlyFoodUSD: 400,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 100,
      monthlyOtherUSD: 250,
      colIndex: 42,
      internetSpeedMbps: 75,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 66,
      safetyIndex: 52,
      healthcareIndex: 68,
      climateScore: 78,
      englishFriendly: true,
      timeZone: "America/Costa_Rica",
      timeZoneOffsetHours: -6,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Costa Rica Digital Nomad Visa (Rentista)",
      visaRequirements: "Proof of min $3,000/month income, health insurance",
      maxStayDays: 365,
      visaFeeUSD: 100,
      citizenshipPathYears: 7,
    },
    pros: ["0% tax on foreign income", "Biodiversity and nature", "Stable democracy", "Pura vida lifestyle"],
    cons: ["San Jose is not very attractive", "Traffic", "Infrastructure gaps outside capital", "Safety varies"],
  },
  {
    id: "mu-mauritius",
    city: "Mauritius",
    country: "Mauritius",
    countryCode: "MU",
    emoji: "🇲🇺",
    region: "Africa",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      flatRate: 0.15,
      socialSecurityRate: 0.03,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "IN", "ZA", "CN", "AU"],
      specialRegimes: "Premium Visa holders: may only be taxed on Mauritius-sourced income for duration of visa",
      taxResidencyNotes: "15% flat rate on all income. One of the lowest flat rates globally. Extensive treaty network.",
    },
    col: {
      monthlyRentUSD: 1100,
      monthlyFoodUSD: 400,
      monthlyTransportUSD: 100,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 300,
      colIndex: 46,
      internetSpeedMbps: 55,
      coworkingDayPassUSD: 20,
    },
    qol: {
      qualityOfLifeScore: 68,
      safetyIndex: 68,
      healthcareIndex: 65,
      climateScore: 88,
      englishFriendly: true,
      timeZone: "Indian/Mauritius",
      timeZoneOffsetHours: 4,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Premium Visa",
      visaRequirements: "Remote workers. $1,500/month min income. Application online.",
      maxStayDays: 365,
      visaFeeUSD: 0,
      citizenshipPathYears: undefined,
    },
    pros: ["15% flat tax", "Free Premium Visa for nomads", "Tropical paradise", "Safe and stable"],
    cons: ["Island isolation", "Expensive imports", "Small local economy", "Limited coworking options"],
  },
  {
    id: "za-cape-town",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    emoji: "🇿🇦",
    region: "Africa",
    tags: ["low-cost", "english-friendly", "warm-climate"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 237100, rate: 0.18 },
        { min: 237100, max: 370500, rate: 0.26 },
        { min: 370500, max: 512800, rate: 0.31 },
        { min: 512800, max: 673000, rate: 0.36 },
        { min: 673000, max: 857900, rate: 0.39 },
        { min: 857900, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.01,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "AU", "IN", "CN"],
      taxResidencyNotes: "Tax on worldwide income for residents. ZAR brackets, calculated in USD equivalent. High earners face up to 45% + skills development levy.",
    },
    col: {
      monthlyRentUSD: 800,
      monthlyFoodUSD: 300,
      monthlyTransportUSD: 100,
      monthlyUtilitiesUSD: 100,
      monthlyOtherUSD: 250,
      colIndex: 36,
      internetSpeedMbps: 55,
      coworkingDayPassUSD: 14,
    },
    qol: {
      qualityOfLifeScore: 60,
      safetyIndex: 30,
      healthcareIndex: 62,
      climateScore: 85,
      englishFriendly: true,
      timeZone: "Africa/Johannesburg",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Remote workers can visit on a tourist visa for 90 days. Long-stay requires critical skills visa.",
      maxStayDays: 90,
      citizenshipPathYears: 5,
    },
    pros: ["Beautiful scenery", "Very affordable", "English-speaking", "World-class wines and food"],
    cons: ["High crime rates (serious)", "Load shedding (power outages)", "Infrastructure challenges", "No nomad visa"],
  },
  {
    id: "at-vienna",
    city: "Vienna",
    country: "Austria",
    countryCode: "AT",
    emoji: "🇦🇹",
    region: "Europe",
    tags: ["high-quality", "eu", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 11693, rate: 0 },
        { min: 11693, max: 19134, rate: 0.20 },
        { min: 19134, max: 32075, rate: 0.30 },
        { min: 32075, max: 62080, rate: 0.415 },
        { min: 62080, max: 93120, rate: 0.48 },
        { min: 93120, max: 1000000, rate: 0.50 },
        { min: 1000000, max: null, rate: 0.55 },
      ],
      socialSecurityRate: 0.185,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU"],
      taxResidencyNotes: "Very high income taxes. Top rate reaches 55% for million+ earners. Social security on top of that.",
    },
    col: {
      monthlyRentUSD: 1600,
      monthlyFoodUSD: 550,
      monthlyTransportUSD: 75,
      monthlyUtilitiesUSD: 160,
      monthlyOtherUSD: 380,
      colIndex: 62,
      internetSpeedMbps: 85,
      coworkingDayPassUSD: 28,
    },
    qol: {
      qualityOfLifeScore: 88,
      safetyIndex: 83,
      healthcareIndex: 90,
      climateScore: 60,
      englishFriendly: true,
      timeZone: "Europe/Vienna",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Austria Freelancer Visa",
      visaRequirements: "Proof of freelance income, health insurance, accommodation",
      maxStayDays: 365,
      visaFeeUSD: 160,
      citizenshipPathYears: 10,
    },
    pros: ["Ranked world's most liveable city", "Excellent healthcare", "World-class culture", "EU access"],
    cons: ["Very high taxes", "Expensive", "German language required for integration", "Bureaucracy"],
  },
  {
    id: "fr-paris",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    emoji: "🇫🇷",
    region: "Europe",
    tags: ["high-quality", "eu", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 11294, rate: 0 },
        { min: 11294, max: 28797, rate: 0.11 },
        { min: 28797, max: 82341, rate: 0.30 },
        { min: 82341, max: 177106, rate: 0.41 },
        { min: 177106, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.098,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "JP", "CN", "AU", "CA"],
      specialRegimes: "Impatriate regime: 30% exemption on French-source income for 5 years for qualifying new residents",
      taxResidencyNotes: "Resident after 183 days or economic center in France. Impatriate regime available for those first taking up employment in France.",
    },
    col: {
      monthlyRentUSD: 2000,
      monthlyFoodUSD: 650,
      monthlyTransportUSD: 100,
      monthlyUtilitiesUSD: 160,
      monthlyOtherUSD: 450,
      colIndex: 73,
      internetSpeedMbps: 130,
      coworkingDayPassUSD: 35,
    },
    qol: {
      qualityOfLifeScore: 80,
      safetyIndex: 60,
      healthcareIndex: 88,
      climateScore: 62,
      englishFriendly: true,
      timeZone: "Europe/Paris",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Talent Visa (Passeport Talent) for freelancers with French clients/projects",
      citizenshipPathYears: 5,
    },
    pros: ["World-class culture and food", "Excellent healthcare", "EU access", "Impatriate tax regime"],
    cons: ["Very expensive", "High taxes", "Strikes and social unrest common", "Bureaucracy"],
  },
  {
    id: "jp-tokyo",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    emoji: "🇯🇵",
    region: "Asia",
    tags: ["tech-friendly", "high-quality", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 1950000, rate: 0.05 },
        { min: 1950000, max: 3300000, rate: 0.10 },
        { min: 3300000, max: 6950000, rate: 0.20 },
        { min: 6950000, max: 9000000, rate: 0.23 },
        { min: 9000000, max: 18000000, rate: 0.33 },
        { min: 18000000, max: 40000000, rate: 0.40 },
        { min: 40000000, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.015,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "AU", "CA", "SG", "KR"],
      taxResidencyNotes: "Resident after 183 days. 10% local (inhabitant) tax on top of national income tax. Combined rates can reach 55%.",
    },
    col: {
      monthlyRentUSD: 1600,
      monthlyFoodUSD: 550,
      monthlyTransportUSD: 120,
      monthlyUtilitiesUSD: 150,
      monthlyOtherUSD: 400,
      colIndex: 65,
      internetSpeedMbps: 200,
      coworkingDayPassUSD: 30,
    },
    qol: {
      qualityOfLifeScore: 84,
      safetyIndex: 92,
      healthcareIndex: 88,
      climateScore: 68,
      englishFriendly: false,
      timeZone: "Asia/Tokyo",
      timeZoneOffsetHours: 9,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Japan Digital Nomad Visa",
      visaRequirements: "Employment contract with foreign company, min $68,000/year income",
      maxStayDays: 180,
      visaFeeUSD: 75,
      citizenshipPathYears: 10,
    },
    pros: ["Extremely safe", "Incredible food and culture", "World-class tech infrastructure", "Unique experience"],
    cons: ["High total tax burden", "Language barrier", "Bureaucracy", "Expensive if not careful", "Earthquake risk"],
  },
  {
    id: "kr-seoul",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    emoji: "🇰🇷",
    region: "Asia",
    tags: ["tech-friendly", "high-quality"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 14000000, rate: 0.06 },
        { min: 14000000, max: 50000000, rate: 0.15 },
        { min: 50000000, max: 88000000, rate: 0.24 },
        { min: 88000000, max: 150000000, rate: 0.35 },
        { min: 150000000, max: 300000000, rate: 0.38 },
        { min: 300000000, max: 500000000, rate: 0.40 },
        { min: 500000000, max: null, rate: 0.42 },
      ],
      socialSecurityRate: 0.045,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU", "SG"],
      taxResidencyNotes: "KRW brackets, converted to USD. Local inhabitant tax (10% of income tax) added. Combined effective rate can be high.",
    },
    col: {
      monthlyRentUSD: 1500,
      monthlyFoodUSD: 500,
      monthlyTransportUSD: 80,
      monthlyUtilitiesUSD: 140,
      monthlyOtherUSD: 350,
      colIndex: 60,
      internetSpeedMbps: 270,
      coworkingDayPassUSD: 22,
    },
    qol: {
      qualityOfLifeScore: 80,
      safetyIndex: 82,
      healthcareIndex: 82,
      climateScore: 65,
      englishFriendly: false,
      timeZone: "Asia/Seoul",
      timeZoneOffsetHours: 9,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Korea Digital Nomad Visa (D-8-4)",
      visaRequirements: "Minimum annual income of $65,000, employment with non-Korean company",
      maxStayDays: 365,
      visaFeeUSD: 60,
      citizenshipPathYears: 5,
    },
    pros: ["Fastest internet in the world", "Safe and modern", "Excellent healthcare", "Amazing food"],
    cons: ["Language barrier", "High social conformity pressure", "Cold winters", "Progressive taxes"],
  },
  {
    id: "nz-auckland",
    city: "Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    emoji: "🇳🇿",
    region: "Oceania",
    tags: ["english-friendly", "high-quality", "warm-climate"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 14000, rate: 0.105 },
        { min: 14000, max: 48000, rate: 0.175 },
        { min: 48000, max: 70000, rate: 0.30 },
        { min: 70000, max: 180000, rate: 0.33 },
        { min: 180000, max: null, rate: 0.39 },
      ],
      socialSecurityRate: 0.00,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "AU", "DE", "JP", "CN", "SG"],
      taxResidencyNotes: "No social security contributions from employees. GST (15%) on goods/services but not on income.",
    },
    col: {
      monthlyRentUSD: 1900,
      monthlyFoodUSD: 650,
      monthlyTransportUSD: 130,
      monthlyUtilitiesUSD: 150,
      monthlyOtherUSD: 400,
      colIndex: 72,
      internetSpeedMbps: 100,
      coworkingDayPassUSD: 30,
    },
    qol: {
      qualityOfLifeScore: 84,
      safetyIndex: 78,
      healthcareIndex: 82,
      climateScore: 75,
      englishFriendly: true,
      timeZone: "Pacific/Auckland",
      timeZoneOffsetHours: 12,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Working Holiday Visa (under 35), Skilled Migrant Category, or Accredited Employer Work Visa",
      citizenshipPathYears: 5,
    },
    pros: ["Beautiful nature", "Safe and stable", "English-speaking", "High quality of life"],
    cons: ["Very expensive", "Remote location", "No nomad visa", "Housing crisis"],
  },
  {
    id: "ch-zurich",
    city: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    emoji: "🇨🇭",
    region: "Europe",
    tags: ["high-quality", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 17800, rate: 0.00 },
        { min: 17800, max: 31600, rate: 0.077 },
        { min: 31600, max: 41400, rate: 0.088 },
        { min: 41400, max: 55200, rate: 0.112 },
        { min: 55200, max: 72500, rate: 0.132 },
        { min: 72500, max: 79000, rate: 0.143 },
        { min: 79000, max: 107000, rate: 0.15 },
        { min: 107000, max: null, rate: 0.115 },
      ],
      socialSecurityRate: 0.053,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "JP", "CN", "AU", "SG"],
      taxResidencyNotes: "Federal + cantonal + municipal taxes. Zurich canton rates used. Lump sum taxation available for wealthy non-working residents.",
    },
    col: {
      monthlyRentUSD: 3500,
      monthlyFoodUSD: 900,
      monthlyTransportUSD: 200,
      monthlyUtilitiesUSD: 250,
      monthlyOtherUSD: 600,
      colIndex: 110,
      internetSpeedMbps: 150,
      coworkingDayPassUSD: 50,
    },
    qol: {
      qualityOfLifeScore: 94,
      safetyIndex: 90,
      healthcareIndex: 94,
      climateScore: 65,
      englishFriendly: true,
      timeZone: "Europe/Zurich",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: false,
      citizenshipPathYears: 10,
    },
    pros: ["Highest quality of life in the world", "Excellent healthcare", "Very safe", "Beautiful Alpine scenery"],
    cons: ["Most expensive city in the world", "No nomad visa", "High income + local taxes", "Can feel sterile"],
  },
  {
    id: "uk-london",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    emoji: "🇬🇧",
    region: "Europe",
    tags: ["english-friendly", "tech-friendly", "high-quality"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 12570, rate: 0 },
        { min: 12570, max: 50270, rate: 0.20 },
        { min: 50270, max: 125140, rate: 0.40 },
        { min: 125140, max: null, rate: 0.45 },
      ],
      socialSecurityRate: 0.12,
      employerPays: false,
      hasTaxTreaty: ["US", "DE", "FR", "JP", "AU", "CA", "SG", "IN"],
      taxResidencyNotes: "National Insurance contributions up to 12% on top of income tax. Domicile-based taxation for non-UK domiciled individuals allows remittance basis (only pay UK tax on UK income + remitted foreign income).",
    },
    col: {
      monthlyRentUSD: 2800,
      monthlyFoodUSD: 750,
      monthlyTransportUSD: 200,
      monthlyUtilitiesUSD: 200,
      monthlyOtherUSD: 500,
      colIndex: 88,
      internetSpeedMbps: 130,
      coworkingDayPassUSD: 40,
    },
    qol: {
      qualityOfLifeScore: 80,
      safetyIndex: 65,
      healthcareIndex: 80,
      climateScore: 40,
      englishFriendly: true,
      timeZone: "Europe/London",
      timeZoneOffsetHours: 0,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Global Talent Visa, Skilled Worker Visa, or Self-Employed/Freelancer route under Innovator Founder",
      citizenshipPathYears: 5,
    },
    pros: ["World-class financial hub", "Diverse culture", "English-speaking", "Non-dom tax regime for foreigners"],
    cons: ["Very expensive", "Weather", "Up to 45%+12% NI tax", "Housing crisis"],
  },
  {
    id: "hr-dubrovnik",
    city: "Dubrovnik",
    country: "Croatia",
    countryCode: "HR",
    emoji: "🇭🇷",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "eu"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 50400, rate: 0.20 },
        { min: 50400, max: null, rate: 0.30 },
      ],
      socialSecurityRate: 0.20,
      employerPays: false,
      hasTaxTreaty: ["DE", "AT", "FR", "UK", "US"],
      specialRegimes: "Digital Nomad Visa holders (up to 1 year): may be exempt from Croatian income tax if not establishing tax residency",
      taxResidencyNotes: "Digital nomad visa is non-tax-resident status — foreign income not taxed in Croatia for visa holders.",
      remoteWorkerRegime: "Digital Nomad Visa: 0% Croatian tax if maintaining tax residency elsewhere",
    },
    col: {
      monthlyRentUSD: 1100,
      monthlyFoodUSD: 450,
      monthlyTransportUSD: 60,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 280,
      colIndex: 48,
      internetSpeedMbps: 80,
      coworkingDayPassUSD: 18,
    },
    qol: {
      qualityOfLifeScore: 70,
      safetyIndex: 78,
      healthcareIndex: 68,
      climateScore: 82,
      englishFriendly: true,
      timeZone: "Europe/Zagreb",
      timeZoneOffsetHours: 1,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Croatia Digital Nomad Visa",
      visaRequirements: "Min income of ~$2,500/month. Work for non-Croatian employer.",
      maxStayDays: 365,
      visaFeeUSD: 50,
      citizenshipPathYears: 8,
    },
    pros: ["Beautiful Adriatic coastline", "EU member", "0% tax for visa holders", "Mediterranean lifestyle"],
    cons: ["Expensive in tourist season", "Limited urban infrastructure", "Visa requires you stay non-resident"],
  },
  {
    id: "ar-buenos-aires",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    emoji: "🇦🇷",
    region: "Americas",
    tags: ["low-cost", "warm-climate", "english-friendly"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 5000, rate: 0 },
        { min: 5000, max: 25000, rate: 0.05 },
        { min: 25000, max: 50000, rate: 0.09 },
        { min: 50000, max: 75000, rate: 0.12 },
        { min: 75000, max: 100000, rate: 0.15 },
        { min: 100000, max: null, rate: 0.35 },
      ],
      socialSecurityRate: 0.11,
      employerPays: false,
      hasTaxTreaty: ["DE", "ES", "FR", "IT", "AU"],
      taxResidencyNotes: "Argentina taxes worldwide income for residents. However, currency controls mean many remote workers use the parallel 'blue dollar' rate, significantly reducing effective local cost. Tax enforcement is limited for foreign-income earners.",
    },
    col: {
      monthlyRentUSD: 500,
      monthlyFoodUSD: 250,
      monthlyTransportUSD: 30,
      monthlyUtilitiesUSD: 60,
      monthlyOtherUSD: 150,
      colIndex: 24,
      internetSpeedMbps: 55,
      coworkingDayPassUSD: 8,
    },
    qol: {
      qualityOfLifeScore: 58,
      safetyIndex: 42,
      healthcareIndex: 60,
      climateScore: 75,
      englishFriendly: false,
      timeZone: "America/Argentina/Buenos_Aires",
      timeZoneOffsetHours: -3,
    },
    visa: {
      hasDigitalNomadVisa: false,
      visaRequirements: "Stay up to 3 months as tourist. Digital nomad visa bill proposed but not yet in force.",
      maxStayDays: 90,
      citizenshipPathYears: 2,
    },
    pros: ["Cheapest major city for USD earners", "European culture and food", "Vibrant arts scene", "Warm climate"],
    cons: ["Economic instability and inflation", "Crime in certain areas", "No formal nomad visa", "Language barrier"],
  },
  {
    id: "gr-athens",
    city: "Athens",
    country: "Greece",
    countryCode: "GR",
    emoji: "🇬🇷",
    region: "Europe",
    tags: ["digital-nomad-visa", "low-tax", "warm-climate", "eu"],
    tax: {
      taxationType: "worldwide",
      taxBrackets: [
        { min: 0, max: 10000, rate: 0.09 },
        { min: 10000, max: 20000, rate: 0.22 },
        { min: 20000, max: 30000, rate: 0.28 },
        { min: 30000, max: 40000, rate: 0.36 },
        { min: 40000, max: null, rate: 0.44 },
      ],
      socialSecurityRate: 0.143,
      employerPays: false,
      hasTaxTreaty: ["US", "UK", "DE", "FR", "AU", "CA"],
      specialRegimes: "Non-Dom Regime: 7% flat rate on foreign pension/income for 15 years for new residents",
      taxResidencyNotes: "Non-Dom: Foreign income taxed at flat 7% for qualifying residents who transfer tax residency to Greece. Digital nomads may apply.",
      remoteWorkerRegime: "Digital Nomad Regime: 50% income tax exemption for the first 7 years",
    },
    col: {
      monthlyRentUSD: 850,
      monthlyFoodUSD: 380,
      monthlyTransportUSD: 50,
      monthlyUtilitiesUSD: 120,
      monthlyOtherUSD: 250,
      colIndex: 40,
      internetSpeedMbps: 70,
      coworkingDayPassUSD: 15,
    },
    qol: {
      qualityOfLifeScore: 68,
      safetyIndex: 70,
      healthcareIndex: 65,
      climateScore: 88,
      englishFriendly: true,
      timeZone: "Europe/Athens",
      timeZoneOffsetHours: 2,
    },
    visa: {
      hasDigitalNomadVisa: true,
      visaName: "Greece Digital Nomad Visa",
      visaRequirements: "Proof of remote employment, min €3,500/month income",
      maxStayDays: 365,
      visaFeeUSD: 75,
      citizenshipPathYears: 7,
    },
    pros: ["50% income tax exemption for nomads (7 years)", "Ancient history and culture", "Mediterranean climate", "EU access"],
    cons: ["Economic challenges", "Slower internet", "Administrative inefficiency", "Higher social security"],
  },
];

export function getLocationById(id: string): LocationData | undefined {
  return LOCATIONS.find((l) => l.id === id);
}

export function getLocationStats() {
  const withNomadVisa = LOCATIONS.filter((l) => l.visa.hasDigitalNomadVisa).length;
  const lowestTax = LOCATIONS.reduce((prev, curr) =>
    (curr.tax.flatRate ?? 0.25) < (prev.tax.flatRate ?? 0.25) ? curr : prev
  );
  const highestQol = LOCATIONS.reduce((prev, curr) =>
    curr.qol.qualityOfLifeScore > prev.qol.qualityOfLifeScore ? curr : prev
  );
  const cheapest = LOCATIONS.reduce((prev, curr) => {
    const prevTotal = prev.col.monthlyRentUSD + prev.col.monthlyFoodUSD + prev.col.monthlyTransportUSD;
    const currTotal = curr.col.monthlyRentUSD + curr.col.monthlyFoodUSD + curr.col.monthlyTransportUSD;
    return currTotal < prevTotal ? curr : prev;
  });
  const regions = [...new Set(LOCATIONS.map((l) => l.region))];

  return {
    totalLocations: LOCATIONS.length,
    locationsWithNomadVisa: withNomadVisa,
    lowestTaxLocation: `${lowestTax.city}, ${lowestTax.country}`,
    highestQolLocation: `${highestQol.city}, ${highestQol.country}`,
    cheapestLocation: `${cheapest.city}, ${cheapest.country}`,
    regions,
  };
}
